Remove empty values from the options.
python-visualization/folium pull request #2049
Opened 2024-12-12 19:28 UTC by hansthen

@Conengmo can you have a look at this? I still need to update four tests because we now remove the `None` values.

2024-12-12 21:18 UTC, Conengmo commented
Yes this makes a lot of sense. I also think this is the way to go for this. I assume you put the new function in all places that used to haven parse options?

I’ll do a full review tomorrow morning, just wanted to say I think this is a good approach.

2024-12-13 11:51 UTC, Conengmo requested changes
Great work! Good approach and very thorough. I tried finding instances where we had `parse_options` before and are not adding `remove_empty` now, to see if there's a potential issue. Found only one possible mark:

- I think you missed adding `remove_empty` in `plugins/semicircle.py`. That used to have a `parse_options` call and it seems to have values that are None.

After we get this merged, I'll go ahead and make a v0.19.2 release.

2024-12-13 14:10 UTC, hansthen commented
> Great work! Good approach and very thorough. I tried finding instances where we had `parse_options` before #2029 and are not adding `remove_empty` now, to see if there's a potential issue. Found only one possible mark:
> 
> * I think you missed adding `remove_empty` in `plugins/semicircle.py`. That used to have a `parse_options` call and it seems to have values that are None.
> 
> After we get this merged, I'll go ahead and make a v0.19.2 release.

Thanks for the compliments. I felt a tad guilty for breaking the release :-(.

2024-12-13 14:20 UTC, Conengmo commented on folium/plugins/semicircle.py
> +        self.options = remove_empty(self.options)
```suggestion
        self.options = remove_empty(**self.options)
```

2024-12-13 14:31 UTC, Conengmo approved these changes
> I felt a tad guilty for breaking the release :-(.

No worries, those things happen :) I developed a bit of a paranoia about big changes for this reason. But I don't want development to stop because something could go wrong!

That said, a more complete test suite would help here. But doing integration tests in Selenium is much work and quite fragile. Maybe something to think about how we could set that up properly.

2024-12-13 14:32 UTC, Conengmo commented
@hansthen do you want to take a final look and merge? If you can't get to it today, I'll merge this one in a bit. I'll make a release afterwards.

2024-12-13 14:48 UTC, merged

2024-12-13 14:54 UTC, hansthen commented
> > I felt a tad guilty for breaking the release :-(.
> 
> No worries, those things happen :) I developed a bit of a paranoia about big changes for this reason. But I don't want development to stop because something could go wrong!
> 
> That said, a more complete test suite would help here. But doing integration tests in Selenium is much work and quite fragile. Maybe something to think about how we could set that up properly.

`streamlit-folium` uses `playwright`. I found it quite intuitive. It has a recording mode and a visual playback mode, which makes it easy to debug failing tests. It is not perfect, I found that tests can break randomly due to changes in underlying components, but rather easy to fix.